/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package desafiocodigobanco;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import desafiocodigobanco.Cadastro.CadastroCliente;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
       // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testeCadastro(){
        CadastroCliente cc = new CadastroCliente();
        Assertions.assertEquals(cc.getClass(), cc.getClass());
    }
}
