/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package desafiocodigobanco;

import desafiocodigobanco.Visoes.MainView;

public class App {
    public static void main(String[] args) {
        MainView mv = new MainView();

        mv.MenuPrincipal();
    }
}